11/07/2019 21:51:03 - System.Data.SqlClient.SqlException (0x80131904): Invalid column name 'Nombre Usuarioc'.
   en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   en System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   en System.Data.SqlClient.SqlDataReader.get_MetaData()
   en System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   en System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   en System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   en System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   en System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   en System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   en System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   en System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   en System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)
   en Japolingo_0._0._1.Implementaciones.SQLConexion.select(String Sselect, String[] parameters) en C:\Users\energ\Desktop\TFGJ\07-07-2019\japroyecto\Japolingo_0.0.1\Implementaciones\SQLConexion.cs:línea 62
ClientConnectionId:748cf58e-14b6-4786-a9f5-026513a4c822
Error Number:207,State:1,Class:16
11/07/2019 21:51:04 - System.IndexOutOfRangeException: No hay ninguna fila en la posición 0.
   en System.Data.RBTree`1.GetNodeByIndex(Int32 userIndex)
   en System.Data.DataRowCollection.get_Item(Int32 index)
   en Japolingo_0._0._1.Implementaciones.Nivel.NivelSelect(String usuario) en C:\Users\energ\Desktop\TFGJ\07-07-2019\japroyecto\Japolingo_0.0.1\Implementaciones\Nivel.cs:línea 22
11/07/2019 22:40:13 - System.InvalidOperationException: La conexión no se cerró. El estado actual de la conexión es abierta.
   en System.Data.ProviderBase.DbConnectionInternal.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   en System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   en System.Data.SqlClient.SqlConnection.Open()
   en Japolingo_0._0._1.Implementaciones.SQLConexion.executeNonQuery(String insertString) en C:\Users\energ\Desktop\TFGJ\07-07-2019\japroyecto\Japolingo_0.0.1\Implementaciones\SQLConexion.cs:línea 120
